---
kind: pipeline
type: docker
name: build-amd64

platform:
  arch: amd64

steps:
  - name: make dist
    image: ghcr.io/alkk/netxms-make-dist:latest
    commands:
      - V=$(fgrep 'Version:' SPECS/netxms.spec|cut -d':' -f2|tr -d [:space:])
      - "[ -z $V ] && echo Cannot detect release, check spec file && exit 1"
      - /build.sh release-$V
      - cp netxms/netxms-$V.tar.gz SOURCES/
  - name: build
    image: ghcr.io/netxms/rpm-builder:latest
    privileged: true
    commands:
      - /build.sh
      - mkdir -p /drone/src/result
      - cp /var/lib/mock/rocky+epel-*-aarch64/result/*.rpm /drone/src/result/
  - name: copy resulting rpm files to staging area
    image: ghcr.io/alkk/drone-rsync:latest
    settings:
      hosts: ["10.3.0.15"]
      user: rpm-staging
      key:
        from_secret: deploy_key
      source: /drone/src/result/*.rpm
      target: /staging/rpm
      delete: true
---
kind: pipeline
type: docker
name: build-arm64

platform:
  arch: arm64

steps:
  - name: make dist
    image: ghcr.io/alkk/netxms-make-dist:latest
    commands:
      - V=$(fgrep 'Version:' SPECS/netxms.spec|cut -d':' -f2|tr -d [:space:])
      - "[ -z $V ] && echo Cannot detect release, check spec file && exit 1"
      - /build.sh release-$V
      - cp netxms/netxms-$V.tar.gz SOURCES/
  - name: build
    image: ghcr.io/netxms/rpm-builder:latest
    privileged: true
    commands:
      - /build.sh
      - mkdir -p /drone/src/result
      - cp /var/lib/mock/rocky+epel-*-aarch64/result/*.rpm /drone/src/result/
  - name: copy resulting rpm files to staging area
    image: ghcr.io/alkk/drone-rsync:latest
    settings:
      hosts: ["10.3.0.15"]
      user: rpm-staging
      key:
        from_secret: deploy_key
      source: /drone/src/result/*.rpm
      target: /staging/rpm
      delete: true

---
kind: pipeline
name: notify after
type: docker
steps:
  - name: notify
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: telegram_bot_token
      to:
        from_secret: telegram_channel_id
      disable_web_page_preview: true

depends_on:
  - build-amd64
  - build-arm64

---
kind: signature
hmac: b7c067166256641d5fdf6e3f849538685dddf71802de517ba3578e5ea9b46412
