---
kind: pipeline
type: docker
name: build-amd64

platform:
  arch: amd64

volumes:
  - name: result
    temp: {}
  - name: cache
    host:
      path: /cache/builder-rpm

steps:
  - name: make dist
    image: ghcr.io/alkk/netxms-make-dist:latest
    commands:
      - V=$(fgrep 'Version:' SPECS/netxms.spec|cut -d':' -f2|tr -d [:space:])
      - "[ -z $V ] && echo Cannot detect release, check spec file && exit 1"
      - /build.sh release-$V
      - cp netxms/netxms-$V.tar.gz SOURCES/
  - name: build-epel
    image: ghcr.io/netxms/builder-rpm:1.15
    privileged: true
    volumes:
      - name: result
        path: /result
      - name: cache
        path: /var/cache/mock
      - name: sources
        path: /drone/src/SOURCES
    commands:
      - /build.sh --target epel
  - name: build-fedora
    image: ghcr.io/netxms/builder-rpm:1.15
    privileged: true
    volumes:
      - name: result
        path: /result
      - name: cache
        path: /var/cache/mock
      - name: sources
        path: /drone/src/SOURCES
    commands:
      - /build.sh --target fedora
  - name: upload
    image: ghcr.io/alkk/drone-rsync:latest
    volumes:
      - name: result
        path: /result
    settings:
      host:
        from_secret: deploy_target
      host_fingerprint:
        from_secret: deploy_host_fingerprint
      port:
        from_secret: deploy_port
      user:
        from_secret: deploy_user
      key:
        from_secret: deploy_key
      source: /result/*.rpm
      destination: /staging/rpm
      delete: true
      extra: --verbose --chmod=Dg+w,Fg+w
    depends_on:
      - build-epel
      - build-fedora

---
kind: pipeline
type: docker
name: build-arm64

platform:
  arch: arm64

volumes:
  - name: result
    temp: {}
  - name: cache
    host:
      path: /cache/builder-rpm

steps:
  - name: make dist
    image: ghcr.io/alkk/netxms-make-dist:latest
    commands:
      - V=$(fgrep 'Version:' SPECS/netxms.spec|cut -d':' -f2|tr -d [:space:])
      - "[ -z $V ] && echo Cannot detect release, check spec file && exit 1"
      - /build.sh release-$V
      - cp netxms/netxms-$V.tar.gz SOURCES/
  - name: build-epel
    image: ghcr.io/netxms/builder-rpm:1.15
    privileged: true
    volumes:
      - name: result
        path: /result
      - name: cache
        path: /var/cache/mock
      - name: sources
        path: /drone/src/SOURCES
    commands:
      - /build.sh --target epel
  - name: build-fedora
    image: ghcr.io/netxms/builder-rpm:1.15
    privileged: true
    volumes:
      - name: result
        path: /result
      - name: cache
        path: /var/cache/mock
      - name: sources
        path: /drone/src/SOURCES
    commands:
      - /build.sh --target fedora
  - name: upload
    image: ghcr.io/alkk/drone-rsync:latest
    volumes:
      - name: result
        path: /result
    settings:
      host:
        from_secret: deploy_target
      host_fingerprint:
        from_secret: deploy_host_fingerprint
      port:
        from_secret: deploy_port
      user:
        from_secret: deploy_user
      key:
        from_secret: deploy_key
      source: /result/*.rpm
      destination: /staging/rpm
      delete: true
      extra: --verbose --chmod=Dg+w,Fg+w
    depends_on:
      - build-epel
      - build-fedora

---
kind: pipeline
name: notify
type: docker
steps:
  - name: notify
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: telegram_bot_token
      to:
        from_secret: telegram_channel_id
      disable_web_page_preview: true

trigger:
  status:
    - success
    - failure

depends_on:
  - build-amd64
  - build-arm64

---
kind: signature
hmac: 28ad713d06036be6183ecc5cae9b5c59909ee12dd3dd4286aa3c38150175ec7c

...
