---
kind: pipeline
type: docker
name: build-amd64

platform:
  arch: amd64

volumes:
  - name: result
    temp: {}
  - name: m2-repo
    host:
      path: /cache/m2-repo

steps:
  - name: make-dist
    image: ghcr.io/alkk/netxms-make-dist:latest
    commands:
      - V=$(fgrep 'Version:' SPECS/netxms.spec|cut -d':' -f2|tr -d [:space:])
      - "[ -z $V ] && echo Cannot detect release, check spec file && exit 1"
      - /build.sh release-$V
      - cp netxms/netxms-$V.tar.gz SOURCES/
  - name: build-ol8
    image: oraclelinux:8
    volumes:
      - name: result
        path: /result
      - name: m2-repo
        path: /m2-repo
    commands:
      - scripts/build-rpm.sh epel 8
    depends_on:
      - make-dist
  - name: build-ol9
    image: oraclelinux:9
    volumes:
      - name: result
        path: /result
      - name: m2-repo
        path: /m2-repo
    commands:
      - scripts/build-rpm.sh epel 9
    depends_on:
      - make-dist
  - name: build-ol10
    image: oraclelinux:10
    volumes:
      - name: result
        path: /result
      - name: m2-repo
        path: /m2-repo
    commands:
      - scripts/build-rpm.sh epel 10
    depends_on:
      - make-dist
  - name: build-fedora42
    image: fedora:42
    volumes:
      - name: result
        path: /result
      - name: m2-repo
        path: /m2-repo
    commands:
      - scripts/build-rpm.sh fedora 42
    depends_on:
      - make-dist
  - name: build-fedora43
    image: fedora:43
    volumes:
      - name: result
        path: /result
      - name: m2-repo
        path: /m2-repo
    commands:
      - scripts/build-rpm.sh fedora 43
    depends_on:
      - make-dist
  - name: upload
    image: ghcr.io/alkk/drone-rsync:latest
    volumes:
      - name: result
        path: /result
    settings:
      host:
        from_secret: deploy_target
      host_fingerprint:
        from_secret: deploy_host_fingerprint
      port:
        from_secret: deploy_port
      user:
        from_secret: deploy_user
      key:
        from_secret: deploy_key
      source: /result/*.rpm
      destination: /staging/rpm
      delete: true
      extra: --verbose --chmod=Dg+w,Fg+w
    depends_on:
      - build-ol8
      - build-ol9
      - build-ol10
      - build-fedora42
      - build-fedora43

---
kind: pipeline
type: docker
name: build-arm64

platform:
  arch: arm64

volumes:
  - name: result
    temp: {}
  - name: m2-repo
    host:
      path: /cache/m2-repo

steps:
  - name: make-dist
    image: ghcr.io/alkk/netxms-make-dist:latest
    commands:
      - V=$(fgrep 'Version:' SPECS/netxms.spec|cut -d':' -f2|tr -d [:space:])
      - "[ -z $V ] && echo Cannot detect release, check spec file && exit 1"
      - /build.sh release-$V
      - cp netxms/netxms-$V.tar.gz SOURCES/
  - name: build-ol8
    image: oraclelinux:8
    volumes:
      - name: result
        path: /result
      - name: m2-repo
        path: /m2-repo
    commands:
      - scripts/build-rpm.sh epel 8
    depends_on:
      - make-dist
  - name: build-ol9
    image: oraclelinux:9
    volumes:
      - name: result
        path: /result
      - name: m2-repo
        path: /m2-repo
    commands:
      - scripts/build-rpm.sh epel 9
    depends_on:
      - make-dist
  - name: build-ol10
    image: oraclelinux:10
    volumes:
      - name: result
        path: /result
      - name: m2-repo
        path: /m2-repo
    commands:
      - scripts/build-rpm.sh epel 10
    depends_on:
      - make-dist
  - name: build-fedora42
    image: fedora:42
    volumes:
      - name: result
        path: /result
      - name: m2-repo
        path: /m2-repo
    commands:
      - scripts/build-rpm.sh fedora 42
    depends_on:
      - make-dist
  - name: build-fedora43
    image: fedora:43
    volumes:
      - name: result
        path: /result
      - name: m2-repo
        path: /m2-repo
    commands:
      - scripts/build-rpm.sh fedora 43
    depends_on:
      - make-dist
  - name: upload
    image: ghcr.io/alkk/drone-rsync:latest
    volumes:
      - name: result
        path: /result
    settings:
      host:
        from_secret: deploy_target
      host_fingerprint:
        from_secret: deploy_host_fingerprint
      port:
        from_secret: deploy_port
      user:
        from_secret: deploy_user
      key:
        from_secret: deploy_key
      source: /result/*.rpm
      destination: /staging/rpm
      delete: true
      extra: --verbose --chmod=Dg+w,Fg+w
    depends_on:
      - build-ol8
      - build-ol9
      - build-ol10
      - build-fedora42
      - build-fedora43

---
kind: pipeline
name: notify
type: docker
steps:
  - name: notify
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: telegram_bot_token
      to:
        from_secret: telegram_channel_id
      disable_web_page_preview: true

trigger:
  status:
    - success
    - failure

depends_on:
  - build-amd64
  - build-arm64

...
