---
kind: pipeline
type: docker
name: build-amd64

platform:
  arch: amd64

volumes:
  - name: m2-repo-ol8
    host:
      path: /cache/m2-repo/ol8
  - name: m2-repo-ol9
    host:
      path: /cache/m2-repo/ol9
  - name: m2-repo-ol10
    host:
      path: /cache/m2-repo/ol10
  - name: m2-repo-fedora42
    host:
      path: /cache/m2-repo/fedora42
  - name: m2-repo-fedora43
    host:
      path: /cache/m2-repo/fedora43

steps:
  - name: make-dist
    image: ghcr.io/alkk/netxms-make-dist:latest
    commands:
      - V=$(fgrep 'Version:' SPECS/netxms.spec|cut -d':' -f2|tr -d [:space:])
      - "[ -z $V ] && echo Cannot detect release, check spec file && exit 1"
      - /build.sh release-$V
      - cp netxms/netxms-$V.tar.gz SOURCES/
      - rm -rf netxms
  - name: build-ol8
    image: ghcr.io/netxms/builder-rpm:epel8
    volumes:
      - name: m2-repo-ol8
        path: /m2-repo
    commands:
      - dnf builddep -y SPECS/netxms.spec
      - mkdir -p BUILD-el8
      - rpmbuild --define "_topdir $(pwd)" --define "_builddir $(pwd)/BUILD-el8" -ba SPECS/netxms.spec
      - rm -rf BUILD-el8
    depends_on:
      - make-dist
  - name: build-ol9
    image: ghcr.io/netxms/builder-rpm:epel9
    volumes:
      - name: m2-repo-ol9
        path: /m2-repo
    commands:
      - dnf builddep -y SPECS/netxms.spec
      - mkdir -p BUILD-el9
      - rpmbuild --define "_topdir $(pwd)" --define "_builddir $(pwd)/BUILD-el9" -ba SPECS/netxms.spec
      - rm -rf BUILD-el9
    depends_on:
      - make-dist
  - name: build-ol10
    image: ghcr.io/netxms/builder-rpm:epel10
    volumes:
      - name: m2-repo-ol10
        path: /m2-repo
    commands:
      - dnf builddep -y SPECS/netxms.spec
      - mkdir -p BUILD-el10
      - rpmbuild --define "_topdir $(pwd)" --define "_builddir $(pwd)/BUILD-el10" -ba SPECS/netxms.spec
      - rm -rf BUILD-el10
    depends_on:
      - make-dist
  - name: build-fedora42
    image: ghcr.io/netxms/builder-rpm:fedora42
    volumes:
      - name: m2-repo-fedora42
        path: /m2-repo
    commands:
      - dnf builddep -y SPECS/netxms.spec
      - mkdir -p BUILD-fc42
      - rpmbuild --define "_topdir $(pwd)" --define "_builddir $(pwd)/BUILD-fc42" -ba SPECS/netxms.spec
      - rm -rf BUILD-fc42
    depends_on:
      - make-dist
  - name: build-fedora43
    image: ghcr.io/netxms/builder-rpm:fedora43
    volumes:
      - name: m2-repo-fedora43
        path: /m2-repo
    commands:
      - dnf builddep -y SPECS/netxms.spec
      - mkdir -p BUILD-fc43
      - rpmbuild --define "_topdir $(pwd)" --define "_builddir $(pwd)/BUILD-fc43" -ba SPECS/netxms.spec
      - rm -rf BUILD-fc43
    depends_on:
      - make-dist
  - name: upload
    image: ghcr.io/alkk/drone-rsync:latest
    settings:
      host:
        from_secret: deploy_target
      host_fingerprint:
        from_secret: deploy_host_fingerprint
      port:
        from_secret: deploy_port
      user:
        from_secret: deploy_user
      key:
        from_secret: deploy_key
      source:
        - RPMS/x86_64/
      destination: /staging/rpm
      delete: true
      extra: --verbose --chmod=Dg+w,Fg+w
    depends_on:
      - build-ol8
      - build-ol9
      - build-ol10
      - build-fedora42
      - build-fedora43

---
kind: pipeline
type: docker
name: build-arm64

platform:
  arch: arm64

volumes:
  - name: m2-repo-ol8
    host:
      path: /tmp/cache/m2-repo/ol8
  - name: m2-repo-ol9
    host:
      path: /tmp/cache/m2-repo/ol9
  - name: m2-repo-ol10
    host:
      path: /tmp/cache/m2-repo/ol10
  - name: m2-repo-fedora42
    host:
      path: /tmp/cache/m2-repo/fedora42
  - name: m2-repo-fedora43
    host:
      path: /tmp/cache/m2-repo/fedora43

steps:
  - name: make-dist
    image: ghcr.io/alkk/netxms-make-dist:latest
    commands:
      - V=$(fgrep 'Version:' SPECS/netxms.spec|cut -d':' -f2|tr -d [:space:])
      - "[ -z $V ] && echo Cannot detect release, check spec file && exit 1"
      - /build.sh release-$V
      - cp netxms/netxms-$V.tar.gz SOURCES/
      - rm -rf netxms
  - name: build-ol8
    image: ghcr.io/netxms/builder-rpm:epel8
    volumes:
      - name: m2-repo-ol8
        path: /m2-repo
    commands:
      - dnf builddep -y SPECS/netxms.spec
      - mkdir -p BUILD-el8
      - rpmbuild --define "_topdir $(pwd)" --define "_builddir $(pwd)/BUILD-el8" -ba SPECS/netxms.spec
      - rm -rf BUILD-el8
    depends_on:
      - make-dist
  - name: build-ol9
    image: ghcr.io/netxms/builder-rpm:epel9
    volumes:
      - name: m2-repo-ol9
        path: /m2-repo
    commands:
      - dnf builddep -y SPECS/netxms.spec
      - mkdir -p BUILD-el9
      - rpmbuild --define "_topdir $(pwd)" --define "_builddir $(pwd)/BUILD-el9" -ba SPECS/netxms.spec
      - rm -rf BUILD-el9
    depends_on:
      - make-dist
  - name: build-ol10
    image: ghcr.io/netxms/builder-rpm:epel10
    volumes:
      - name: m2-repo-ol10
        path: /m2-repo
    commands:
      - dnf builddep -y SPECS/netxms.spec
      - mkdir -p BUILD-el10
      - rpmbuild --define "_topdir $(pwd)" --define "_builddir $(pwd)/BUILD-el10" -ba SPECS/netxms.spec
      - rm -rf BUILD-el10
    depends_on:
      - make-dist
  - name: build-fedora42
    image: ghcr.io/netxms/builder-rpm:fedora42
    volumes:
      - name: m2-repo-fedora42
        path: /m2-repo
    commands:
      - dnf builddep -y SPECS/netxms.spec
      - mkdir -p BUILD-fc42
      - rpmbuild --define "_topdir $(pwd)" --define "_builddir $(pwd)/BUILD-fc42" -ba SPECS/netxms.spec
      - rm -rf BUILD-fc42
    depends_on:
      - make-dist
  - name: build-fedora43
    image: ghcr.io/netxms/builder-rpm:fedora43
    volumes:
      - name: m2-repo-fedora43
        path: /m2-repo
    commands:
      - dnf builddep -y SPECS/netxms.spec
      - mkdir -p BUILD-fc43
      - rpmbuild --define "_topdir $(pwd)" --define "_builddir $(pwd)/BUILD-fc43" -ba SPECS/netxms.spec
      - rm -rf BUILD-fc43
    depends_on:
      - make-dist
  - name: upload
    image: ghcr.io/alkk/drone-rsync:latest
    settings:
      host:
        from_secret: deploy_target
      host_fingerprint:
        from_secret: deploy_host_fingerprint
      port:
        from_secret: deploy_port
      user:
        from_secret: deploy_user
      key:
        from_secret: deploy_key
      source:
        - RPMS/aarch64/
      destination: /staging/rpm
      delete: true
      extra: --verbose --chmod=Dg+w,Fg+w
    depends_on:
      - build-ol8
      - build-ol9
      - build-ol10
      - build-fedora42
      - build-fedora43

---
kind: pipeline
name: notify
type: docker
steps:
  - name: notify
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: telegram_bot_token
      to:
        from_secret: telegram_channel_id
      disable_web_page_preview: true

trigger:
  status:
    - success
    - failure

depends_on:
  - build-amd64
  - build-arm64

---
kind: signature
hmac: ea5ec329f7df5656fc16787a8427738252e948340f270cbbdf5ef4100145d82c

...
