---
kind: pipeline
type: docker
name: build-amd64

platform:
  arch: amd64

volumes:
  - name: result
    temp: {}
  - name: cache
    host:
      path: /cache/builder-rpm

steps:
  - name: make dist
    image: ghcr.io/alkk/netxms-make-dist:latest
    commands:
      - V=$(fgrep 'Version:' SPECS/netxms.spec|cut -d':' -f2|tr -d [:space:])
      - "[ -z $V ] && echo Cannot detect release, check spec file && exit 1"
      - /build.sh release-$V
      - cp netxms/netxms-$V.tar.gz SOURCES/
  - name: build
    image: ghcr.io/netxms/builder-rpm:latest
    privileged: true
    volumes:
      - name: result
        path: /result
      - name: cache
        path: /var/cache/mock
    commands:
      - /build.sh
      - cp /var/lib/mock/*/result/*.rpm /result/
  - name: upload
    image: ghcr.io/alkk/drone-rsync:latest
    volumes:
      - name: result
        path: /result
    settings:
      host:
        from_secret: deploy_target
      host_fingerprint: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICEyadn+aPSVLesBCB1CN6mm5x593YFpAu4swBv8er5A
      port:
        from_secret: deploy_port
      user:
        from_secret: deploy_user
      key:
        from_secret: deploy_key
      source: /result/*.rpm
      destination: /staging/rpm
      delete: true
      extra: --verbose --chmod=Dg+w,Fg+w

---
kind: pipeline
type: docker
name: build-arm64

platform:
  arch: arm64

volumes:
  - name: result
    temp: {}
  - name: cache
    host:
      path: /cache/builder-rpm

steps:
  - name: make dist
    image: ghcr.io/alkk/netxms-make-dist:latest
    commands:
      - V=$(fgrep 'Version:' SPECS/netxms.spec|cut -d':' -f2|tr -d [:space:])
      - "[ -z $V ] && echo Cannot detect release, check spec file && exit 1"
      - /build.sh release-$V
      - cp netxms/netxms-$V.tar.gz SOURCES/
  - name: build
    image: ghcr.io/netxms/builder-rpm:latest
    privileged: true
    volumes:
      - name: result
        path: /result
      - name: cache
        path: /var/cache/mock
    commands:
      - /build.sh
      - cp /var/lib/mock/*/result/*.rpm /result/
  - name: upload
    image: ghcr.io/alkk/drone-rsync:latest
    volumes:
      - name: result
        path: /result
    settings:
      host:
        from_secret: deploy_target
      host_fingerprint: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICEyadn+aPSVLesBCB1CN6mm5x593YFpAu4swBv8er5A
      port:
        from_secret: deploy_port
      user:
        from_secret: deploy_user
      key:
        from_secret: deploy_key
      source: /result/*.rpm
      destination: /staging/rpm
      delete: true
      extra: --verbose --chmod=Dg+w,Fg+w

---
kind: pipeline
name: notify
type: docker
steps:
  - name: notify
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: telegram_bot_token
      to:
        from_secret: telegram_channel_id
      disable_web_page_preview: true

depends_on:
  - build-amd64
  - build-arm64

---
kind: signature
hmac: dbdd54008a9502165e54106eb050bb34ede988c7a94998a5452cce59f6a4ba1b

...
